export { default as ContactAdd } from './contactAdd/ContactAdd'
export { default as Contact } from './contact/Contact'
export { default as NotFound } from './notFound/NotFound'
export { default as Reminder } from './reminder/Reminder'
export { default as Menu } from './menu/Menu'
