export { default as PageWithOptions } from './PageWithOptions/PageWithOptions'
export { default as Layout } from './Layout/Layout'
export { default as ReminderInfo } from './ReminderInfo/ReminderInfo'
export { default as WhatsAppButton } from './WhatsAppButton/WhatsAppButton'
export { default as AceptCancelButtons } from './AceptCancelButtons/AceptCancelButtons'
